# Generated by Django 4.1.3 on 2022-12-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0002_alter_tweet_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweet",
            options={"ordering": ["-created_at"]},
        ),
    ]
